inherit = "config/common/vad.toml"

[meta]
save_dir = "experiments"
use_amp = false

[model]
path = "model.vad_model.CrnVad"
[model.args]
rnn_layers=2
rnn_units=128
kernel_num=[1, 32, 64, 128, 256,]
fc_hidden_dim=128
fft_len=320
look_ahead=2
use_offline_norm = true
use_cumulative_norm = false
spec_size=80

[train_dataset]
[train_dataset.args]
clean_dataset = "/media/administrator/Data/LibriSpeech/train-clean-360_wav"

[train_dataset.dataloader]
batch_size = 16
num_workers = 0
shuffle = true

[trainer]
path = "trainer.vad_trainer.Trainer"
[trainer.train]
save_checkpoint_interval = 1
[trainer.validation]
validation_interval = 1
[trainer.visualization]
num_workers = 0